/** @file

  Copyright 2016 Unified EFI, Inc.<BR>
  Copyright (c) 2016, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "Hash2BBTestMain.h"

EFI_GUID gHash2BBTestConformanceAssertionGuid001 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_001_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid002 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_002_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid003 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_003_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid004 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_004_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid005 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_005_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid006 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_006_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid007 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_007_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid008 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_008_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid009 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_009_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid010 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_010_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid011 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_011_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid012 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_012_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid013 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_013_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid014 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_014_GUID;
EFI_GUID gHash2BBTestConformanceAssertionGuid015 = EFI_TEST_HASH2BBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gHash2BBTestFunctionAssertionGuid001 = EFI_TEST_HASH2BBTESTFUNCTION_ASSERTION_001_GUID;
EFI_GUID gHash2BBTestFunctionAssertionGuid002 = EFI_TEST_HASH2BBTESTFUNCTION_ASSERTION_002_GUID;
EFI_GUID gHash2BBTestFunctionAssertionGuid003 = EFI_TEST_HASH2BBTESTFUNCTION_ASSERTION_003_GUID;