/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2018, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "SimpleTextInputExBBTestMain.h"

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid001 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid002 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid003 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid004 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid005 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid006 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid007 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid008 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid009 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gSimpleTextInputExBBTestConformanceAssertionGuid010 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid001 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid002 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid003 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid004 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid005 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid006 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid007 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid008 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid009 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid010 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gSimpleTextInputExBBTestFunctionAssertionGuid011 = EFI_TEST_SIMPLETEXTINPUTEXBBTESTFUNCTION_ASSERTION_011_GUID;
