/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid051 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_051_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid052 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_052_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid053 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_053_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid054 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_054_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid055 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_055_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid056 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_056_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid057 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_057_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid058 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_058_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid059 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_059_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid060 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_060_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid061 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_061_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid062 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_062_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid063 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_063_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid064 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_064_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid065 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_065_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid066 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_066_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid067 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_067_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid068 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_068_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid069 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_069_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid070 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_070_GUID;

EFI_GUID  gDevicePathUtilitiesBBTestFunctionAssertionGuid071 = EFI_TEST_DEVICEPATHUTILITIESBBTESTFUNCTION_ASSERTION_071_GUID;
