/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2011 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gBlockIo2ConformanceTestAssertionGuid001 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid002 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid003 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid004 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid005 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid006 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid007 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid008 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid009 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_009_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid010 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_010_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid011 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_011_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid012 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_012_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid013 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_013_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid014 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_014_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid015 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_015_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid016 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_016_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid017 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_017_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid018 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_018_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid019 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_019_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid020 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_020_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid021 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_021_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid022 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_022_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid023 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_023_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid024 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_024_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid025 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_025_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid026 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_026_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid027 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_027_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid028 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_028_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid029 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_029_GUID;

EFI_GUID gBlockIo2ConformanceTestAssertionGuid030 = EFI_TEST_BLOCKIO2CONFORMANCETEST_ASSERTION_030_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid001 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_001_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid002 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_002_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid003 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_003_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid004 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_004_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid005 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_005_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid006 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_006_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid007 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_007_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid008 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_008_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid009 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_009_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid010 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_010_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid011 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_011_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid012 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_012_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid013 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_013_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid014 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_014_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid015 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_015_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid016 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_016_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid017 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_017_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid018 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_018_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid019 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_019_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid020 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_020_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid021 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_021_GUID;

EFI_GUID gBlockIo2FunctionTestAssertionGuid022 = EFI_TEST_BLOCKIO2FUNCTIONTEST_ASSERTION_022_GUID;
