/** @file

  Copyright 2006 - 2015 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gSerialIoBbTestFunctionAssertionGuid001 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid002 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid003 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid004 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid005 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid006 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid007 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid008 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid009 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid010 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid011 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid012 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid013 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid014 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid015 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid016 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gSerialIoBbTestFunctionAssertionGuid017 = EFI_TEST_SERIALIOBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid001 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid002 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid003 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid004 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid005 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid006 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid007 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid008 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid009 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid010 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gSerialIoBbTestConformanceAssertionGuid011 = EFI_TEST_SERIALIOBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid001 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_001_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid002 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_002_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid003 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_003_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid004 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_004_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid005 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_005_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid006 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_006_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid007 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_007_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid008 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_008_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid009 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_009_GUID;

EFI_GUID gSerialIoBbTestStressAssertionGuid010 = EFI_TEST_SERIALIOBBTESTSTRESS_ASSERTION_010_GUID;
