/** @file

  Copyright 2006 - 2015 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gUsbIoTestConformanceAssertionGuid001 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid002 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid003 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid004 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid005 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid006 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid007 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid008 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid009 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid010 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid011 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid012 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid013 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid014 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid015 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid016 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid017 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid018 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid019 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid020 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid021 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid022 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid023 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid024 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid025 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid026 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid027 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid028 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid029 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid030 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_030_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid031 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_031_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid032 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_032_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid033 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_033_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid034 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_034_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid035 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_035_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid036 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_036_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid037 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_037_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid038 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_038_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid039 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_039_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid040 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_040_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid041 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_041_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid042 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_042_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid043 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_043_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid044 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_044_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid045 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_045_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid046 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_046_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid047 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_047_GUID;

EFI_GUID gUsbIoTestConformanceAssertionGuid048 = EFI_TEST_USBIOTESTCONFORMANCE_ASSERTION_048_GUID;

