/** @file

  Copyright 2006 - 2015 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for UEFI test assertion.

 --*/

#include "Efi.h"
#include "Guid.h"

EFI_GUID  gUsb2HcTestBasicAssertionGuid001        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_001_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid002        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_002_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid003        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_003_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid004        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_004_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid005        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_005_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid006        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_006_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid007        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_007_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid008        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_008_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid009        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_009_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid010        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_010_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid011        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_011_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid012        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_012_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid013        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_013_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid014        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_014_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid015        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_015_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid016        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_016_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid017        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_017_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid018        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_018_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid019        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_019_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid020        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_020_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid021        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_021_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid022        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_022_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid023        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_023_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid024        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_024_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid025        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_025_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid026        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_026_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid027        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_027_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid028        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_028_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid029        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_029_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid030        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_030_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid031        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_031_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid032        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_032_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid033        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_033_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid034        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_034_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid035        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_035_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid036        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_036_GUID;

EFI_GUID  gUsb2HcTestBasicAssertionGuid037        = EFI_TEST_USB2HCTESTBASIC_ASSERTION_037_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid001  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid002  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid003  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid004  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid005  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid006  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid007  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid008  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid009  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid010  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid011  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid012  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid013  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid014  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid015  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid016  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid017  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid018  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid019  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid020  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid021  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid022  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid023  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid024  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid025  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid026  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid027  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid028  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid029  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid030  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_030_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid031  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_031_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid032  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_032_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid033  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_033_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid034  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_034_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid035  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_035_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid036  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_036_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid037  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_037_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid038  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_038_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid039  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_039_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid040  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_040_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid041  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_041_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid042  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_042_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid043  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_043_GUID;

EFI_GUID  gUsb2HcTestConformanceAssertionGuid044  = EFI_TEST_USB2HCTESTCONFORMANCE_ASSERTION_044_GUID;

