/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gUsbHcTestBasicAssertionGuid001 = EFI_TEST_USBHCTESTBASIC_ASSERTION_001_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid002 = EFI_TEST_USBHCTESTBASIC_ASSERTION_002_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid003 = EFI_TEST_USBHCTESTBASIC_ASSERTION_003_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid004 = EFI_TEST_USBHCTESTBASIC_ASSERTION_004_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid005 = EFI_TEST_USBHCTESTBASIC_ASSERTION_005_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid006 = EFI_TEST_USBHCTESTBASIC_ASSERTION_006_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid007 = EFI_TEST_USBHCTESTBASIC_ASSERTION_007_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid008 = EFI_TEST_USBHCTESTBASIC_ASSERTION_008_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid009 = EFI_TEST_USBHCTESTBASIC_ASSERTION_009_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid010 = EFI_TEST_USBHCTESTBASIC_ASSERTION_010_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid011 = EFI_TEST_USBHCTESTBASIC_ASSERTION_011_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid012 = EFI_TEST_USBHCTESTBASIC_ASSERTION_012_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid013 = EFI_TEST_USBHCTESTBASIC_ASSERTION_013_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid014 = EFI_TEST_USBHCTESTBASIC_ASSERTION_014_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid015 = EFI_TEST_USBHCTESTBASIC_ASSERTION_015_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid016 = EFI_TEST_USBHCTESTBASIC_ASSERTION_016_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid017 = EFI_TEST_USBHCTESTBASIC_ASSERTION_017_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid018 = EFI_TEST_USBHCTESTBASIC_ASSERTION_018_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid019 = EFI_TEST_USBHCTESTBASIC_ASSERTION_019_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid020 = EFI_TEST_USBHCTESTBASIC_ASSERTION_020_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid021 = EFI_TEST_USBHCTESTBASIC_ASSERTION_021_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid022 = EFI_TEST_USBHCTESTBASIC_ASSERTION_022_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid023 = EFI_TEST_USBHCTESTBASIC_ASSERTION_023_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid024 = EFI_TEST_USBHCTESTBASIC_ASSERTION_024_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid025 = EFI_TEST_USBHCTESTBASIC_ASSERTION_025_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid026 = EFI_TEST_USBHCTESTBASIC_ASSERTION_026_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid027 = EFI_TEST_USBHCTESTBASIC_ASSERTION_027_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid028 = EFI_TEST_USBHCTESTBASIC_ASSERTION_028_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid029 = EFI_TEST_USBHCTESTBASIC_ASSERTION_029_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid030 = EFI_TEST_USBHCTESTBASIC_ASSERTION_030_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid031 = EFI_TEST_USBHCTESTBASIC_ASSERTION_031_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid032 = EFI_TEST_USBHCTESTBASIC_ASSERTION_032_GUID;

EFI_GUID gUsbHcTestBasicAssertionGuid033 = EFI_TEST_USBHCTESTBASIC_ASSERTION_033_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid001 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid002 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid003 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid004 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid005 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid006 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid007 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid008 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid009 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid010 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid011 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid012 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid013 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid014 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid015 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid016 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid017 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid018 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid019 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid020 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid021 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid022 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid023 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid024 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid025 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid026 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid027 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid028 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid029 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid030 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_030_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid031 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_031_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid032 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_032_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid033 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_033_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid034 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_034_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid035 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_035_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid036 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_036_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid037 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_037_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid038 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_038_GUID;

EFI_GUID gUsbHcTestConformanceAssertionGuid039 = EFI_TEST_USBHCTESTCONFORMANCE_ASSERTION_039_GUID;

