/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006, 2007, 2008, 2009, 2010, 2011 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010 - 2011, Intel Corporation. All rights reserved.<BR>   
   
--*/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "guid.h"


EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid001 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid002 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid003 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid004 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid005 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid006 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid007 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid008 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid009 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid010 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid011 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid012 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid013 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid014 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid015 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid016 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid017 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid018 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid019 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid020 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid021 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid022 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid023 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid024 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid025 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid026 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid027 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid028 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid029 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid030 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_030_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid031 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_031_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid032 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_032_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid033 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_033_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid034 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_034_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid035 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_035_GUID;

EFI_GUID gPxeBaseCodeBBTestConformanceAssertionGuid036 = EFI_TEST_PXEBASECODEBBTESTCONFORMANCE_ASSERTION_036_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid001 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid002 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid003 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid004 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid005 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid006 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid007 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid008 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid009 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid010 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid011 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid012 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid013 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid014 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid015 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid016 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid017 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid018 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid019 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid020 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid021 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid022 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid023 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid024 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid025 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid026 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid027 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_027_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid028 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_028_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid029 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_029_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid030 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_030_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid031 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_031_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid032 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_032_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid033 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_033_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid034 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_034_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid035 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_035_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid036 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_036_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid037 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_037_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid038 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_038_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid039 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_039_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid040 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_040_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid041 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_041_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid042 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_042_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid043 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_043_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid044 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_044_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid045 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_045_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid046 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_046_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid047 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_047_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid048 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_048_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid049 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_049_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid050 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_050_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid051 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_051_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid052 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_052_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid053 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_053_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid054 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_054_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid055 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_055_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid056 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_056_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid057 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_057_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid058 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_058_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid059 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_059_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid060 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_060_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid061 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_061_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid062 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_062_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid063 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_063_GUID;

EFI_GUID gPxeBaseCodeBBTestFunctionAssertionGuid064 = EFI_TEST_PXEBASECODEBBTESTFUNCTION_ASSERTION_064_GUID;

EFI_GUID gPxeBaseCodeBBTestNewConformanceAssertionGuid001 = EFI_TEST_PXEBASECODEBBTESTNEWCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gPxeBaseCodeBBTestNewConformanceAssertionGuid002 = EFI_TEST_PXEBASECODEBBTESTNEWCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gPxeBaseCodeBBTestNewConformanceAssertionGuid003 = EFI_TEST_PXEBASECODEBBTESTNEWCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gPxeBaseCodeBBTestNewConformanceAssertionGuid004 = EFI_TEST_PXEBASECODEBBTESTNEWCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gPxeBaseCodeBBTestNewConformanceAssertionGuid005 = EFI_TEST_PXEBASECODEBBTESTNEWCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid001 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_001_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid002 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_002_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid003 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_003_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid004 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_004_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid005 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_005_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid006 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_006_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid007 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_007_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid008 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_008_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid009 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_009_GUID;

EFI_GUID gPxeBaseCodeBBTestNewFunctionAssertionGuid010 = EFI_TEST_PXEBASECODEBBTESTNEWFUNCTION_ASSERTION_010_GUID;
