/** @file

  Copyright 2016 Unified EFI, Inc.<BR>
  Copyright (c) 2016, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "NVMEPassThruBBTestMain.h"

EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid001 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_001_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid002 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_002_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid003 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_003_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid004 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_004_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid005 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_005_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid006 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_006_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid007 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_007_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid008 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_008_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid009 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_009_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid010 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_010_GUID;
EFI_GUID gNVMEPassThruBBTestConformanceAssertionGuid011 = EFI_TEST_NVMEBBTESTCONFORMANCE_ASSERTION_011_GUID;


EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid001 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_001_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid002 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_002_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid003 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_003_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid004 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_004_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid005 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_005_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid006 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_006_GUID;
EFI_GUID gNVMEPassThruBBTestFunctionAssertionGuid007 = EFI_TEST_NVMEBBTESTFUNCTION_ASSERTION_007_GUID;