/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gMiscRuntimeServicesInterfaceTestAssertionGuid001 = EFI_TEST_MISCRUNTIMESERVICESINTERFACETEST_ASSERTION_001_GUID;

EFI_GUID gMiscRuntimeServicesInterfaceTestAssertionGuid002 = EFI_TEST_MISCRUNTIMESERVICESINTERFACETEST_ASSERTION_002_GUID;

EFI_GUID gMiscRuntimeServicesCombinationTestAssertionGuid001 = EFI_TEST_MISCRUNTIMESERVICESCOMBINATIONTEST_ASSERTION_001_GUID;

EFI_GUID gMiscRuntimeServicesCombinationTestAssertionGuid002 = EFI_TEST_MISCRUNTIMESERVICESCOMBINATIONTEST_ASSERTION_002_GUID;

EFI_GUID gMiscRuntimeServicesCombinationTestAssertionGuid006 = EFI_TEST_MISCRUNTIMESERVICESCOMBINATIONTEST_ASSERTION_006_GUID;

EFI_GUID gMiscRuntimeServicesCombinationTestAssertionGuid007 = EFI_TEST_MISCRUNTIMESERVICESCOMBINATIONTEST_ASSERTION_007_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid001 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid002 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid003 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid004 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid005 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid006 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid007 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_007_GUID;
	
EFI_GUID gMiscRuntimeServicesBBTestFunctionAssertionGuid008 = EFI_TEST_MISCRUNTIMESERVICESBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gMiscRuntimeServicesBBTestConformanceAssertionGuid001 = EFI_TEST_MISCRUNTIMESERVICESBBTESCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gMiscRuntimeServicesBBTestConformanceAssertionGuid002 = EFI_TEST_MISCRUNTIMESERVICESBBTESCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gMiscRuntimeServicesBBTestConformanceAssertionGuid003 = EFI_TEST_MISCRUNTIMESERVICESBBTESCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gMiscRuntimeServicesBBTestConformanceAssertionGuid004 = EFI_TEST_MISCRUNTIMESERVICESBBTESCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gMiscRuntimeServicesBBTestConformanceAssertionGuid005 = EFI_TEST_MISCRUNTIMESERVICESBBTESCONFORMANCE_ASSERTION_005_GUID;

