/** @file

  Copyright 2006 - 2015 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2019, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include <Base.h>
#include "Efi.h"
#include "Guid.h"

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid081 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_081_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid082 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_082_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid083 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_083_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid084 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_084_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid085 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_085_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid086 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_086_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid087 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_087_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid088 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_088_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid089 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_089_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid090 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_090_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid091 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_091_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid092 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_092_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid093 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_093_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid094 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_094_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid095 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_095_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid096 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_096_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid097 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_097_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid098 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_098_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid099 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_099_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid100 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_100_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid101 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_101_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid102 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_102_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid103 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_103_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid104 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_104_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid105 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_105_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid106 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_106_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid107 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_107_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid108 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_108_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid109 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_109_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid110 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_110_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid111 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_111_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid112 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_112_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid113 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_113_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid114 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_114_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid115 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_115_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid116 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_116_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid117 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_117_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid118 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_118_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid119 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_119_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid120 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_120_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid121 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_121_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid122 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_122_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid123 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_123_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid124 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_124_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid125 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_125_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid126 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_126_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid127 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_127_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid128 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_128_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid129 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_129_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid130 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_130_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid131 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_131_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid132 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_132_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid133 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_133_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid134 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_134_GUID;

EFI_GUID  gDevicePathToTextBBTestFunctionAssertionGuid135 = EFI_TEST_DEVICEPATHTOTEXTBBTESTFUNCTION_ASSERTION_135_GUID;
