/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gBisBBTestCaseAssertionGuid001 = EFI_TEST_BISBBTESTCASE_ASSERTION_001_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid002 = EFI_TEST_BISBBTESTCASE_ASSERTION_002_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid003 = EFI_TEST_BISBBTESTCASE_ASSERTION_003_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid004 = EFI_TEST_BISBBTESTCASE_ASSERTION_004_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid005 = EFI_TEST_BISBBTESTCASE_ASSERTION_005_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid006 = EFI_TEST_BISBBTESTCASE_ASSERTION_006_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid007 = EFI_TEST_BISBBTESTCASE_ASSERTION_007_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid008 = EFI_TEST_BISBBTESTCASE_ASSERTION_008_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid009 = EFI_TEST_BISBBTESTCASE_ASSERTION_009_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid010 = EFI_TEST_BISBBTESTCASE_ASSERTION_010_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid011 = EFI_TEST_BISBBTESTCASE_ASSERTION_011_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid012 = EFI_TEST_BISBBTESTCASE_ASSERTION_012_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid013 = EFI_TEST_BISBBTESTCASE_ASSERTION_013_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid014 = EFI_TEST_BISBBTESTCASE_ASSERTION_014_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid015 = EFI_TEST_BISBBTESTCASE_ASSERTION_015_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid016 = EFI_TEST_BISBBTESTCASE_ASSERTION_016_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid017 = EFI_TEST_BISBBTESTCASE_ASSERTION_017_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid018 = EFI_TEST_BISBBTESTCASE_ASSERTION_018_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid019 = EFI_TEST_BISBBTESTCASE_ASSERTION_019_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid020 = EFI_TEST_BISBBTESTCASE_ASSERTION_020_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid021 = EFI_TEST_BISBBTESTCASE_ASSERTION_021_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid022 = EFI_TEST_BISBBTESTCASE_ASSERTION_022_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid023 = EFI_TEST_BISBBTESTCASE_ASSERTION_023_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid024 = EFI_TEST_BISBBTESTCASE_ASSERTION_024_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid025 = EFI_TEST_BISBBTESTCASE_ASSERTION_025_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid026 = EFI_TEST_BISBBTESTCASE_ASSERTION_026_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid027 = EFI_TEST_BISBBTESTCASE_ASSERTION_027_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid028 = EFI_TEST_BISBBTESTCASE_ASSERTION_028_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid029 = EFI_TEST_BISBBTESTCASE_ASSERTION_029_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid030 = EFI_TEST_BISBBTESTCASE_ASSERTION_030_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid031 = EFI_TEST_BISBBTESTCASE_ASSERTION_031_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid032 = EFI_TEST_BISBBTESTCASE_ASSERTION_032_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid033 = EFI_TEST_BISBBTESTCASE_ASSERTION_033_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid034 = EFI_TEST_BISBBTESTCASE_ASSERTION_034_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid035 = EFI_TEST_BISBBTESTCASE_ASSERTION_035_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid036 = EFI_TEST_BISBBTESTCASE_ASSERTION_036_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid037 = EFI_TEST_BISBBTESTCASE_ASSERTION_037_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid038 = EFI_TEST_BISBBTESTCASE_ASSERTION_038_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid039 = EFI_TEST_BISBBTESTCASE_ASSERTION_039_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid040 = EFI_TEST_BISBBTESTCASE_ASSERTION_040_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid041 = EFI_TEST_BISBBTESTCASE_ASSERTION_041_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid042 = EFI_TEST_BISBBTESTCASE_ASSERTION_042_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid043 = EFI_TEST_BISBBTESTCASE_ASSERTION_043_GUID;

EFI_GUID gBisBBTestCaseAssertionGuid044 = EFI_TEST_BISBBTESTCASE_ASSERTION_044_GUID;
