/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gDeviceIoBBTestConformanceAssertionGuid001 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid002 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid003 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid004 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid005 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid006 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid007 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid008 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid009 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid010 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid011 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid012 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid013 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid014 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid015 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid016 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid017 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid018 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid019 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid020 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid021 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid022 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid023 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid024 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid025 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid026 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid027 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gDeviceIoBBTestConformanceAssertionGuid028 = EFI_TEST_DEVICEIOBBTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid001 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid002 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid003 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid004 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid005 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid006 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid007 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid008 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid009 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid010 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid011 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid012 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid013 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid014 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid015 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid016 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid017 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid018 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid019 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid020 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid021 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid022 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid023 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid024 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid025 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid026 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid027 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_027_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid028 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_028_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid029 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_029_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid030 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_030_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid031 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_031_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid032 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_032_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid033 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_033_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid034 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_034_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid035 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_035_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid036 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_036_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid037 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_037_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid038 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_038_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid039 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_039_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid040 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_040_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid041 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_041_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid042 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_042_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid043 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_043_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid044 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_044_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid045 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_045_GUID;

EFI_GUID gDeviceIoBBTestFunctionAssertionGuid046 = EFI_TEST_DEVICEIOBBTESTFUNCTION_ASSERTION_046_GUID;
