/** @file

  Copyright 2006 - 2011 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2018, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "HIIConfigRoutingBBTestMain.h"

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid001 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid002 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid003 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_003_GUID;
/*
EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid004 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid005 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid006 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_006_GUID;
*/
EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid007 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid008 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid009 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid010 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid011 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid012 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid013 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid014 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid015 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid016 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid017 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid018 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid019 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid020 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gHIIConfigRoutingBBTestConformanceAssertionGuid021 = EFI_TEST_HIICONFIGROUTINGBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid001 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid002 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid003 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid004 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid005 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid006 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid007 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid008 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid009 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid010 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gHIIConfigRoutingBBTestFunctionAssertionGuid012 = EFI_TEST_HIICONFIGROUTINGBBTESTFUNCTION_ASSERTION_012_GUID;

