/** @file

  Copyright 2006 - 2026 Unified EFI, Inc.<BR>
  Copyright (c) 2026, AMD Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI REST EX Protocol test assertion.

--*/
#include "Efi.h"
#include "Guid.h"

EFI_GUID gRestExBBTestConformanceAssertionGuid001 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid002 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid003 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid004 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid005 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid006 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid007 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid008 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid009 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid010 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid011 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid012 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gRestExBBTestConformanceAssertionGuid013 = EFI_TEST_REST_EX_BBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid001 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid002 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid003 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid004 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid005 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid006 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid007 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid008 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gRestExBBTestFunctionAssertionGuid009 = EFI_TEST_REST_EX_BBTESTFUNCTION_ASSERTION_009_GUID;
