/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid001 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid002 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid003 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid004 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid005 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid006 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid007 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid008 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid009 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid010 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gAtaPassThruBBTestFunctionAssertionGuid011 = EFI_TEST_ATAPASSTHRUBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid001 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid002 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid003 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid004 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid005 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid006 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid007 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid008 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid009 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid010 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid011 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid012 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid013 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid014 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid015 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid016 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid017 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid018 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid019 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid020 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gAtaPassThruBBTestConformanceAssertionGuid021 = EFI_TEST_ATAPASSTHRUBBTESTCONFORMANCE_ASSERTION_021_GUID;


