/** @file

  Copyright 2006 - 2017 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2017, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "DevicePathBBTestMain.h"

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid001 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid002 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid003 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid004 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid005 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid006 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid007 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid008 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid009 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid010 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid011 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid012 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid013 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid014 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid015 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid016 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid017 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid018 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid019 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid020 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid021 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid022 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid023 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid024 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid025 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid026 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid027 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_027_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid028 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_028_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid029 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_029_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid040 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_040_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid041 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_041_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid042 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_042_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid043 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_043_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid044 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_044_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid045 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_045_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid046 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_046_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid047 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_047_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid048 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_048_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid049 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_049_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid050 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_050_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid052 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_052_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid051 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_051_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid053 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_053_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid054 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_054_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid055 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_055_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid056 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_056_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid057 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_057_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid058 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_058_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid059 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_059_GUID;

EFI_GUID  gDevicePathBBTestFunctionAssertionGuid060 = EFI_TEST_DEVICEPATHBBTESTFUNCTION_ASSERTION_060_GUID;
