/** @file

  Copyright 2017 Unified EFI, Inc.<BR>
  Copyright (c) 2017, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "SDMMCPassThruBBTestMain.h"

EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid001 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_001_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid002 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_002_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid003 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_003_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid004 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_004_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid005 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_005_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid006 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_006_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid007 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_007_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid008 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_008_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid009 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_009_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid010 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_010_GUID;
EFI_GUID gSDMMCPassThruBBTestConformanceAssertionGuid011 = EFI_TEST_SDMMC_PASSTHRU_BBTESTCONFORMANCE_ASSERTION_011_GUID;


EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid001 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_001_GUID;
EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid002 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_002_GUID;
EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid003 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_003_GUID;
EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid004 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_004_GUID;
EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid005 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_005_GUID;
EFI_GUID gSDMMCPassThruBBTestFunctionAssertionGuid006 = EFI_TEST_SDMMC_PASSTHRU_BBTESTFUNCTION_ASSERTION_006_GUID;