/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gUgaDrawConformanceTestAssertionGuid001 = EFI_TEST_UGADRAWCONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gUgaDrawConformanceTestAssertionGuid002 = EFI_TEST_UGADRAWCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gUgaDrawConformanceTestAssertionGuid003 = EFI_TEST_UGADRAWCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gUgaDrawConformanceTestAssertionGuid004 = EFI_TEST_UGADRAWCONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gUgaDrawConformanceTestAssertionGuid005 = EFI_TEST_UGADRAWCONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid003 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_003_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid004 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_004_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid007 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_007_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid008 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_008_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid009 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_009_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid010 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_010_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid011 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_011_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid012 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_012_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid013 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_013_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid014 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_014_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid015 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_015_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid016 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_016_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid020 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_020_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid024 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_024_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid025 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_025_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid026 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_026_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid027 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_027_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid028 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_028_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid029 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_029_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid030 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_030_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid031 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_031_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid032 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_032_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid033 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_033_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid038 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_038_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid042 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_042_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid044 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_044_GUID;

EFI_GUID gUgaDrawExtensiveTestAssertionGuid045 = EFI_TEST_UGADRAWEXTENSIVETEST_ASSERTION_045_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid003 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_003_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid004 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_004_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid005 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_005_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid006 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_006_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid008 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_008_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid009 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_009_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid011 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_011_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid012 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_012_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid014 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_014_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid016 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_016_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid020 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_020_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid021 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_021_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid023 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_023_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid028 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_028_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid032 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_032_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid033 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_033_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid034 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_034_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid036 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_036_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid037 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_037_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid038 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_038_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid040 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_040_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid045 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_045_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid049 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_049_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid050 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_050_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid051 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_051_GUID;

EFI_GUID gUgaDrawInterfaceTestAssertionGuid053 = EFI_TEST_UGADRAWINTERFACETEST_ASSERTION_053_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid001 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid003 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid004 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid005 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid006 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid008 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid009 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gUgaDrawBBTestFunctionAssertionGuid011 = EFI_TEST_UGADRAWBBTESTFUNCTION_ASSERTION_011_GUID;
