/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++
 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "HIIImageBBTestMain.h"

EFI_GUID gHIIImageBBTestConformanceAssertionGuid001 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid002 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid003 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid004 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid005 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid006 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid007 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid008 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid009 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid010 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid011 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid012 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid013 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid014 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid015 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid016 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid017 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid018 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid019 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid020 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid021 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid022 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid023 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid024 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid025 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gHIIImageBBTestConformanceAssertionGuid026 = EFI_TEST_HIIIMAGEBBTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid001 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid002 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid003 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid004 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid005 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid006 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid007 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid008 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gHIIImageBBTestFunctionAssertionGuid009 = EFI_TEST_HIIIMAGEBBTESTFUNCTION_ASSERTION_009_GUID;
