/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006 - 2012 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>   
   
--*/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gPciIoBBTestConformanceAssertionGuid001 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid002 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid003 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid004 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid005 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid006 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid007 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid008 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid009 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid010 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid011 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid012 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid013 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid014 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid015 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid016 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid017 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid018 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid019 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid020 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid021 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid022 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid023 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid024 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid025 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid026 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid027 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid028 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid029 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid030 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_030_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid031 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_031_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid032 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_032_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid033 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_033_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid034 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_034_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid035 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_035_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid036 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_036_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid037 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_037_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid038 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_038_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid039 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_039_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid040 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_040_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid041 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_041_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid042 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_042_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid043 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_043_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid044 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_044_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid045 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_045_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid046 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_046_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid047 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_047_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid048 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_048_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid049 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_049_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid050 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_050_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid051 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_051_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid052 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_052_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid053 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_053_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid054 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_054_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid055 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_055_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid056 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_056_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid057 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_057_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid058 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_058_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid059 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_059_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid060 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_060_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid061 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_061_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid062 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_062_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid063 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_063_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid064 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_064_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid065 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_065_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid066 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_066_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid067 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_067_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid068 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_068_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid069 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_069_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid070 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_070_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid071 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_071_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid072 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_072_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid073 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_073_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid074 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_074_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid075 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_075_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid076 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_076_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid077 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_077_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid078 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_078_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid079 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_079_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid080 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_080_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid081 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_081_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid082 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_082_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid083 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_083_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid084 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_084_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid085 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_085_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid086 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_086_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid087 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_087_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid088 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_088_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid089 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_089_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid090 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_090_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid091 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_091_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid092 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_092_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid093 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_093_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid094 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_094_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid095 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_095_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid096 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_096_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid097 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_097_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid098 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_098_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid099 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_099_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid100 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_100_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid101 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_101_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid102 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_102_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid103 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_103_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid104 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_104_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid105 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_105_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid106 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_106_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid107 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_107_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid108 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_108_GUID;

EFI_GUID gPciIoBBTestConformanceAssertionGuid109 = EFI_TEST_PCIIOBBTESTCONFORMANCE_ASSERTION_109_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid001 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_001_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid002 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_002_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid003 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_003_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid004 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_004_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid005 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_005_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid006 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_006_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid007 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_007_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid008 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_008_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid009 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_009_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid010 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_010_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid011 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_011_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid012 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_012_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid013 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_013_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid014 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_014_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid015 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_015_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid016 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_016_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid017 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_017_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid018 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_018_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid019 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_019_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid020 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_020_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid021 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_021_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid022 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_022_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid023 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_023_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid024 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_024_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid025 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_025_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid026 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_026_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid027 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_027_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid028 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_028_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid029 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_029_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid030 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_030_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid031 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_031_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid032 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_032_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid033 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_033_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid034 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_034_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid035 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_035_GUID;

EFI_GUID gPciIoBBTestFunction_1AssertionGuid036 = EFI_TEST_PCIIOBBTESTFUNCTION_1_ASSERTION_036_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid001 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_001_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid002 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_002_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid003 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_003_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid004 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_004_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid005 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_005_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid006 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_006_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid007 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_007_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid008 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_008_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid009 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_009_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid010 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_010_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid011 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_011_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid012 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_012_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid013 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_013_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid014 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_014_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid015 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_015_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid016 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_016_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid017 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_017_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid018 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_018_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid019 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_019_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid020 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_020_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid021 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_021_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid022 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_022_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid023 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_023_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid024 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_024_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid025 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_025_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid026 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_026_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid027 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_027_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid028 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_028_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid030 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_030_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid031 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_031_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid032 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_032_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid033 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_033_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid034 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_034_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid035 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_035_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid036 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_036_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid037 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_037_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid038 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_038_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid039 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_039_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid040 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_040_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid041 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_041_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid042 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_042_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid043 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_043_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid044 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_044_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid045 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_045_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid046 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_046_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid047 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_047_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid048 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_048_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid049 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_049_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid050 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_050_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid051 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_051_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid052 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_052_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid053 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_053_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid054 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_054_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid055 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_055_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid056 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_056_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid057 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_057_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid058 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_058_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid059 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_059_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid060 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_060_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid061 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_061_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid062 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_062_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid063 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_063_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid064 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_064_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid065 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_065_GUID;

EFI_GUID gPciIoBBTestFunction_2AssertionGuid066 = EFI_TEST_PCIIOBBTESTFUNCTION_2_ASSERTION_066_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid001 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_001_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid002 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_002_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid003 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_003_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid004 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_004_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid005 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_005_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid006 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_006_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid007 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_007_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid008 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_008_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid009 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_009_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid010 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_010_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid011 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_011_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid012 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_012_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid013 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_013_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid014 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_014_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid015 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_015_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid016 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_016_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid017 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_017_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid018 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_018_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid019 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_019_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid020 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_020_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid021 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_021_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid022 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_022_GUID;

EFI_GUID gPciIoBBTestStressAssertionGuid023 = EFI_TEST_PCIIOBBTESTSTRESS_ASSERTION_023_GUID;
