/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006 - 2012 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>   
   
--*/
/*++

Module Name:

  guid_efi.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "SimpleTextOutBBTestMain_efi.h"


EFI_GUID gSimpleTextOutputAssertionGuid001 = EFI_TEST_SIMPLETEXTOUTPUT_ASSERTION_001_GUID;

EFI_GUID gSimpleTextOutputAssertionGuid002 = EFI_TEST_SIMPLETEXTOUTPUT_ASSERTION_002_GUID;

EFI_GUID gSimpleTextOutputAssertionGuid003 = EFI_TEST_SIMPLETEXTOUTPUT_ASSERTION_003_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid001 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid002 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid003 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid004 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid005 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid006 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid007 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid008 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid009 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_009_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid010 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_010_GUID;

EFI_GUID gSimpleTextOutputConformanceTestAssertionGuid011 = EFI_TEST_SIMPLETEXTOUTPUTCONFORMANCETEST_ASSERTION_011_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid001 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_001_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid002 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_002_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid003 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_003_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid004 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_004_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid005 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_005_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid006 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_006_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid007 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_007_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid008 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_008_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid009 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_009_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid010 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_010_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid011 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_011_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid012 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_012_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid013 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_013_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid014 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_014_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid015 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_015_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid016 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_016_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid017 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_017_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid018 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_018_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid019 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_019_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid020 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_020_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid021 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_021_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid022 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_022_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid023 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_023_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid024 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_024_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid025 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_025_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid026 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_026_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid027 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_027_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid028 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_028_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid029 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_029_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid030 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_030_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid031 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_031_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid032 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_032_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid033 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_033_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid034 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_034_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid035 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_035_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid036 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_036_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid037 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_037_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid038 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_038_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid039 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_039_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid040 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_040_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid041 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_041_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid042 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_042_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid043 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_043_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid044 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_044_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid045 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_045_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid046 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_046_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid047 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_047_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid048 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_048_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid049 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_049_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid050 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_050_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid051 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_051_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid052 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_052_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid053 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_053_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid054 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_054_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid055 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_055_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid056 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_056_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid057 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_057_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid058 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_058_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid059 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_059_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid060 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_060_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid061 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_061_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid062 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_062_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid063 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_063_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid064 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_064_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid065 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_065_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid066 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_066_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid067 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_067_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid068 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_068_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid069 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_069_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid070 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_070_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid071 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_071_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid072 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_072_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid073 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_073_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid074 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_074_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid075 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_075_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid076 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_076_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid077 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_077_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid078 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_078_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid079 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_079_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid080 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_080_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid081 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_081_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid082 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_082_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid083 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_083_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid084 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_084_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid085 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_085_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid086 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_086_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid087 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_087_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid088 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_088_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid089 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_089_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid090 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_090_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid091 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_091_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid092 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_092_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid093 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_093_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid094 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_094_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid095 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_095_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid096 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_096_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid097 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_097_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid098 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_098_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid099 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_099_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid100 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_100_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid101 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_101_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid102 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_102_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid103 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_103_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid104 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_104_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid105 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_105_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid106 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_106_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid107 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_107_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid108 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_108_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid109 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_109_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid110 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_110_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid111 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_111_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid112 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_112_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid113 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_113_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid114 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_114_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid115 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_115_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid116 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_116_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid117 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_117_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid118 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_118_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid119 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_119_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid120 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_120_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid121 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_121_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid122 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_122_GUID;

EFI_GUID gSimpleTextOutputFunctionTestAssertionGuid123 = EFI_TEST_SIMPLETEXTOUTPUTFUNCTIONTEST_ASSERTION_123_GUID;
