/** @file

  Copyright 2006 - 2016 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2019, Intel Corporation. All rights reserved.<BR>
  Copyright (c) 2024 HP Development Company, L.P. <BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid_uefi.h"


EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid001 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_001_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid002 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_002_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid003 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_003_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid004 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_004_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid005 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_005_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid006 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_006_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid007 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_007_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid008 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_008_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid009 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_009_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid010 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_010_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid011 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_011_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid012 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_012_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid013 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_013_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid014 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_014_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid015 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_015_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid016 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_016_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid017 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_017_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid018 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_018_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid019 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_019_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid020 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_020_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid021 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_021_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid022 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_022_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid023 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_023_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid024 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_024_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid025 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_025_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid026 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_026_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid027 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_027_GUID;

EFI_GUID gEfiCompliantBbTestPlatformAssertionGuid028 = EFI_TEST_EFICOMPLIANTBBTESTPLATFORM_ASSERTION_028_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid001 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_001_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid002 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_002_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid003 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_003_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid004 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_004_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid005 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_005_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid006 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_006_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid008 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_008_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid009 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_009_GUID;

EFI_GUID gEfiCompliantBbTestRequiredAssertionGuid010 = EFI_TEST_EFICOMPLIANTBBTESTREQUIRED_ASSERTION_010_GUID;
