/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gBlockIoCombinationTestAssertionGuid001 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_001_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid002 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_002_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid003 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_003_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid004 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_004_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid005 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_005_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid006 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_006_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid007 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_007_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid008 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_008_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid009 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_009_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid010 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_010_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid011 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_011_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid012 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_012_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid013 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_013_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid014 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_014_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid015 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_015_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid016 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_016_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid017 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_017_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid018 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_018_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid019 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_019_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid020 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_020_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid021 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_021_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid022 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_022_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid023 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_023_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid024 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_024_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid025 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_025_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid026 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_026_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid027 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_027_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid028 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_028_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid029 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_029_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid030 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_030_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid031 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_031_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid032 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_032_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid033 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_033_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid034 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_034_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid035 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_035_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid036 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_036_GUID;

EFI_GUID gBlockIoCombinationTestAssertionGuid037 = EFI_TEST_BLOCKIOCOMBINATIONTEST_ASSERTION_037_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid001 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid002 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid003 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid004 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid005 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid006 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid007 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid008 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid009 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_009_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid010 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_010_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid011 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_011_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid012 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_012_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid013 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_013_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid014 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_014_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid015 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_015_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid016 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_016_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid017 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_017_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid018 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_018_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid019 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_019_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid020 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_020_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid021 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_021_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid022 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_022_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid023 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_023_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid024 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_024_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid025 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_025_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid026 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_026_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid027 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_027_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid028 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_028_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid029 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_029_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid030 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_030_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid031 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_031_GUID;

EFI_GUID gBlockIoConformanceTestAssertionGuid032 = EFI_TEST_BLOCKIOCONFORMANCETEST_ASSERTION_032_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid001 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_001_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid002 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_002_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid003 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_003_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid004 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_004_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid005 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_005_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid006 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_006_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid007 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_007_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid008 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_008_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid009 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_009_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid010 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_010_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid011 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_011_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid012 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_012_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid013 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_013_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid014 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_014_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid015 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_015_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid016 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_016_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid017 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_017_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid018 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_018_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid019 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_019_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid020 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_020_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid021 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_021_GUID;

EFI_GUID gBlockIoFunctionTestAssertionGuid022 = EFI_TEST_BLOCKIOFUNCTIONTEST_ASSERTION_022_GUID;
