/** @file

  Copyright 2006 - 2011 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2011, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/
#include "Efi.h"
#include "Guid.h"

//
// Conformance Test GUID
//
EFI_GUID gIpSec2BBTestConformanceAssertionGuid001 = EFI_TEST_IPSEC2BBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gIpSec2BBTestConformanceAssertionGuid002 = EFI_TEST_IPSEC2BBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gIpSec2BBTestConformanceAssertionGuid003 = EFI_TEST_IPSEC2BBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gIpSec2BBTestConformanceAssertionGuid004 = EFI_TEST_IPSEC2BBTESTCONFORMANCE_ASSERTION_004_GUID;

//
// Function Test GUID
//
EFI_GUID gIpSec2BBTestFunctionAssertionGuid001 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid002 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid003 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid004 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid005 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid006 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid007 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid008 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid009 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid010 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid011 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid012 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid013 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid014 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid015 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid016 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid017 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid018 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid019 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid020 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid021 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid022 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid023 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid024 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid025 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid026 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID gIpSec2BBTestFunctionAssertionGuid027 = EFI_TEST_IPSEC2BBTESTFUNCTION_ASSERTION_027_GUID;


