/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "HIIFontBBTestMain.h"

EFI_GUID gHIIFontBBTestConformanceAssertionGuid001 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid002 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid003 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid004 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid005 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid006 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid007 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid008 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid009 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid010 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid011 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid012 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid013 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gHIIFontBBTestConformanceAssertionGuid014 = EFI_TEST_HIIFONTBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid001 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid002 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid003 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid004 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid005 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid006 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid007 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid008 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid009 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid010 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid011 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid012 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid013 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid014 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid015 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid016 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid017 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid018 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid019 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid020 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid021 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid022 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid023 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid024 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gHIIFontBBTestFunctionAssertionGuid025 = EFI_TEST_HIIFONTBBTESTFUNCTION_ASSERTION_025_GUID;

