/** @file

  Copyright 2006 - 2015 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid001 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid002 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid003 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid004 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid005 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid006 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid007 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gExtScsiPassThruBBTestFunctionAssertionGuid008 = EFI_TEST_EXTSCSIPASSTHRUBBTESTFUNCTION_ASSERTION_008_GUID;



EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid001 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid002 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid003 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid004 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid005 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid006 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid007 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid008 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid009 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid010 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid011 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid012 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid013 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid014 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid015 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid016 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid017 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid018 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid019 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gExtScsiPassThruBBTestConformanceAssertionGuid020 = EFI_TEST_EXTSCSIPASSTHRUBBTESTCONFORMANCE_ASSERTION_020_GUID;


