/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006 - 2015 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010 - 2015, Intel Corporation. All rights reserved.<BR>   
   
--*/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gSimplePointerConformanceTestAssertionGuid001 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gSimplePointerConformanceTestAssertionGuid002 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gSimplePointerConformanceTestAssertionGuid003 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gSimplePointerConformanceTestAssertionGuid004 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gSimplePointerConformanceTestAssertionGuid005 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gSimplePointerConformanceTestAssertionGuid006 = EFI_TEST_SIMPLEPOINTERCONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid001 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_001_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid002 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_002_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid003 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_003_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid004 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_004_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid005 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_005_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid006 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_006_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid007 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_007_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid008 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_008_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid009 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_009_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid010 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_010_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid011 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_011_GUID;

EFI_GUID gSimplePointerExtensiveTestAssertionGuid012 = EFI_TEST_SIMPLEPOINTEREXTENSIVETEST_ASSERTION_012_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid001 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_001_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid002 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_002_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid003 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_003_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid004 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_004_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid005 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_005_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid006 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_006_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid007 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_007_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid008 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_008_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid009 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_009_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid010 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_010_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid011 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_011_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid012 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_012_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid013 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_013_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid014 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_014_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid015 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_015_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid016 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_016_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid017 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_017_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid018 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_018_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid019 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_019_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid020 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_020_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid021 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_021_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid022 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_022_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid023 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_023_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid024 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_024_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid025 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_025_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid026 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_026_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid027 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_027_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid028 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_028_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid029 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_029_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid030 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_030_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid031 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_031_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid032 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_032_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid033 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_033_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid034 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_034_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid035 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_035_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid036 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_036_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid037 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_037_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid038 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_038_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid039 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_039_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid040 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_040_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid041 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_041_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid042 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_042_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid043 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_043_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid044 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_044_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid045 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_045_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid046 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_046_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid047 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_047_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid048 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_048_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid049 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_049_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid050 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_050_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid051 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_051_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid052 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_052_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid053 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_053_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid054 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_054_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid055 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_055_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid056 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_056_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid057 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_057_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid058 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_058_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid059 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_059_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid060 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_060_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid061 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_061_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid062 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_062_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid063 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_063_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid064 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_064_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid065 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_065_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid066 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_066_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid067 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_067_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid068 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_068_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid069 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_069_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid070 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_070_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid071 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_071_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid072 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_072_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid073 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_073_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid074 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_074_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid075 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_075_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid076 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_076_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid077 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_077_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid078 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_078_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid079 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_079_GUID;

EFI_GUID gSimplePointerInterfaceTestAssertionGuid080 = EFI_TEST_SIMPLEPOINTERINTERFACETEST_ASSERTION_080_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid001 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_001_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid002 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_002_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid003 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_003_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid004 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_004_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid005 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_005_GUID;

EFI_GUID gSimplePointerBBTestStressAssertionGuid006 = EFI_TEST_SIMPLEPOINTERBBTESTSTRESS_ASSERTION_006_GUID;
