/** @file

  Copyright 2006 - 2013 Unified EFI, Inc.<BR>
  Copyright (c) 2013, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"

EFI_GUID gDiskIo2ConformanceTestAssertionGuid001 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid002 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid003 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid004 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid005 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid006 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid007 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid008 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid009 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_009_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid010 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_010_GUID;

EFI_GUID gDiskIo2ConformanceTestAssertionGuid011 = EFI_TEST_DISKIO2CONFORMANCETEST_ASSERTION_011_GUID;


EFI_GUID gDiskIo2FunctionTestAssertionGuid001 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_001_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid002 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_002_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid003 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_003_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid004 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_004_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid005 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_005_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid006 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_006_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid007 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_007_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid008 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_008_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid009 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_009_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid010 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_010_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid011 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_011_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid012 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_012_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid013 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_013_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid014 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_014_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid015 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_015_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid016 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_016_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid017 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_017_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid018 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_018_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid019 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_019_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid020 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_020_GUID;

EFI_GUID gDiskIo2FunctionTestAssertionGuid021 = EFI_TEST_DISKIO2FUNCTIONTEST_ASSERTION_021_GUID;











