/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gDiskIoCombinationTestAssertionGuid001 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_001_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid002 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_002_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid003 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_003_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid004 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_004_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid005 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_005_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid006 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_006_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid009 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_009_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid010 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_010_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid011 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_011_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid012 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_012_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid013 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_013_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid014 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_014_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid015 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_015_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid016 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_016_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid017 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_017_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid018 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_018_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid019 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_019_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid020 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_020_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid021 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_021_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid022 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_022_GUID;

EFI_GUID gDiskIoCombinationTestAssertionGuid023 = EFI_TEST_DISKIOCOMBINATIONTEST_ASSERTION_023_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid001 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_001_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid002 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid003 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid005 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_005_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid006 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_006_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid007 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gDiskIoConformanceTestAssertionGuid008 = EFI_TEST_DISKIOCONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gDiskIoFunctionTestAssertionGuid001 = EFI_TEST_DISKIOFUNCTIONTEST_ASSERTION_001_GUID;

EFI_GUID gDiskIoFunctionTestAssertionGuid003 = EFI_TEST_DISKIOFUNCTIONTEST_ASSERTION_003_GUID;

EFI_GUID gDiskIoFunctionTestAssertionGuid004 = EFI_TEST_DISKIOFUNCTIONTEST_ASSERTION_004_GUID;

EFI_GUID gDiskIoFunctionTestAssertionGuid005 = EFI_TEST_DISKIOFUNCTIONTEST_ASSERTION_005_GUID;

EFI_GUID gDiskIoFunctionTestAssertionGuid006 = EFI_TEST_DISKIOFUNCTIONTEST_ASSERTION_006_GUID;
