/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

 Module Name:

   Guid.c

 Abstract:

   GUIDs auto-generated for EFI test assertion.

--*/

#include "HIIStringBBTestMain.h"

EFI_GUID gHIIStringBBTestConformanceAssertionGuid001 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid002 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid003 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid004 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid005 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid006 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid007 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_007_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid008 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_008_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid009 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_009_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid010 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_010_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid011 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_011_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid012 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_012_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid013 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_013_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid014 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_014_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid015 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_015_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid016 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_016_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid017 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_017_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid018 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_018_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid019 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_019_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid020 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_020_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid021 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_021_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid022 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_022_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid023 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_023_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid024 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_024_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid025 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_025_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid026 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_026_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid027 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_027_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid028 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_028_GUID;

EFI_GUID gHIIStringBBTestConformanceAssertionGuid029 = EFI_TEST_HIISTRINGBBTESTCONFORMANCE_ASSERTION_029_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid001 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid002 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid003 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid004 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid005 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid006 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gHIIStringBBTestFunctionAssertionGuid007 = EFI_TEST_HIISTRINGBBTESTFUNCTION_ASSERTION_007_GUID;

