/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006 - 2012 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>   
   
--*/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gCombinationTestAssertionGuid001 = EFI_TEST_COMBINATIONTEST_ASSERTION_001_GUID;

EFI_GUID gCombinationTestAssertionGuid002 = EFI_TEST_COMBINATIONTEST_ASSERTION_002_GUID;

EFI_GUID gCombinationTestAssertionGuid003 = EFI_TEST_COMBINATIONTEST_ASSERTION_003_GUID;

EFI_GUID gConsistencyTestAssertionGuid001 = EFI_TEST_CONSISTENCYTEST_ASSERTION_001_GUID;

EFI_GUID gConsistencyTestAssertionGuid002 = EFI_TEST_CONSISTENCYTEST_ASSERTION_002_GUID;

EFI_GUID gConsistencyTestAssertionGuid003 = EFI_TEST_CONSISTENCYTEST_ASSERTION_003_GUID;

EFI_GUID gConsistencyTestAssertionGuid004 = EFI_TEST_CONSISTENCYTEST_ASSERTION_004_GUID;

EFI_GUID gConsistencyTestAssertionGuid005 = EFI_TEST_CONSISTENCYTEST_ASSERTION_005_GUID;

EFI_GUID gConsistencyTestAssertionGuid006 = EFI_TEST_CONSISTENCYTEST_ASSERTION_006_GUID;

EFI_GUID gConsistencyTestAssertionGuid007 = EFI_TEST_CONSISTENCYTEST_ASSERTION_007_GUID;

EFI_GUID gConsistencyTestAssertionGuid008 = EFI_TEST_CONSISTENCYTEST_ASSERTION_008_GUID;

EFI_GUID gConsistencyTestAssertionGuid009 = EFI_TEST_CONSISTENCYTEST_ASSERTION_009_GUID;

EFI_GUID gConsistencyTestAssertionGuid010 = EFI_TEST_CONSISTENCYTEST_ASSERTION_010_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid001 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid002 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid003 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid004 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid005 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid006 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid007 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid008 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid009 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid010 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid011 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid012 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid013 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid014 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid015 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid016 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid017 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid018 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid019 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid020 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid021 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid022 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid023 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid024 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid025 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid026 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid027 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_027_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid028 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_028_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid029 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_029_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid030 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_030_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid031 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_031_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid032 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_032_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid033 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_033_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid034 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_034_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid035 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_035_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid036 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_036_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid037 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_037_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid039 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_039_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid040 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_040_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid042 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_042_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid043 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_043_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid044 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_044_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid045 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_045_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid046 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_046_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid047 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_047_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid048 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_048_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid049 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_049_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid050 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_050_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid051 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_051_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid052 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_052_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid053 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_053_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid054 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_054_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid055 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_055_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid056 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_056_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid057 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_057_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid058 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_058_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid059 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_059_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid060 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_060_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid061 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_061_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid062 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_062_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid063 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_063_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid064 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_064_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid065 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_065_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid066 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_066_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid067 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_067_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid068 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_068_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid069 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_069_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid070 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_070_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid071 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_071_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid072 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_072_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid073 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_073_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid074 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_074_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid075 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_075_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid076 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_076_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid077 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_077_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid078 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_078_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid079 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_079_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid080 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_080_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid081 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_081_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid082 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_082_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid083 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_083_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid084 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_084_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid085 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_085_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid086 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_086_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid087 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_087_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid088 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_088_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid089 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_089_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid090 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_090_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid092 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_092_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid094 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_094_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid096 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_096_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid098 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_098_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid100 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_100_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid102 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_102_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid104 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_104_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid106 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_106_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid108 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_108_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid110 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_110_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid112 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_112_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid114 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_114_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid116 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_116_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid118 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_118_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid120 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_120_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid122 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_122_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid124 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_124_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid126 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_126_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid128 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_128_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid130 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_130_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid132 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_132_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid134 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_134_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid136 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_136_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid138 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_138_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid140 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_140_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid142 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_142_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid144 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_144_GUID;

#if (EFI_SPECIFICATION_VERSION >= 0x0002000A)
EFI_GUID gImageBBTestFunctionAssertionGuid145 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_145_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid146 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_146_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid147 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_147_GUID;

EFI_GUID gImageBBTestFunctionAssertionGuid148 = EFI_TEST_IMAGEBBTESTFUNCTION_ASSERTION_148_GUID;
#endif
