/*++
  The material contained herein is not a license, either        
  expressly or impliedly, to any intellectual property owned    
  or controlled by any of the authors or developers of this     
  material or to any contribution thereto. The material         
  contained herein is provided on an "AS IS" basis and, to the  
  maximum extent permitted by applicable law, this information  
  is provided AS IS AND WITH ALL FAULTS, and the authors and    
  developers of this material hereby disclaim all other         
  warranties and conditions, either express, implied or         
  statutory, including, but not limited to, any (if any)        
  implied warranties, duties or conditions of merchantability,  
  of fitness for a particular purpose, of accuracy or           
  completeness of responses, of results, of workmanlike         
  effort, of lack of viruses and of lack of negligence, all     
  with regard to this material and any contribution thereto.    
  Designers must not rely on the absence or characteristics of  
  any features or instructions marked "reserved" or             
  "undefined." The Unified EFI Forum, Inc. reserves any         
  features or instructions so marked for future definition and  
  shall have no responsibility whatsoever for conflicts or      
  incompatibilities arising from future changes to them. ALSO,  
  THERE IS NO WARRANTY OR CONDITION OF TITLE, QUIET ENJOYMENT,  
  QUIET POSSESSION, CORRESPONDENCE TO DESCRIPTION OR            
  NON-INFRINGEMENT WITH REGARD TO THE TEST SUITE AND ANY        
  CONTRIBUTION THERETO.                                         
                                                                
  IN NO EVENT WILL ANY AUTHOR OR DEVELOPER OF THIS MATERIAL OR  
  ANY CONTRIBUTION THERETO BE LIABLE TO ANY OTHER PARTY FOR     
  THE COST OF PROCURING SUBSTITUTE GOODS OR SERVICES, LOST      
  PROFITS, LOSS OF USE, LOSS OF DATA, OR ANY INCIDENTAL,        
  CONSEQUENTIAL, DIRECT, INDIRECT, OR SPECIAL DAMAGES WHETHER   
  UNDER CONTRACT, TORT, WARRANTY, OR OTHERWISE, ARISING IN ANY  
  WAY OUT OF THIS OR ANY OTHER AGREEMENT RELATING TO THIS       
  DOCUMENT, WHETHER OR NOT SUCH PARTY HAD ADVANCE NOTICE OF     
  THE POSSIBILITY OF SUCH DAMAGES.                              
                                                                
  Copyright 2006 - 2015 Unified EFI, Inc. All  
  Rights Reserved, subject to all existing rights in all        
  matters included within this Test Suite, to which United      
  EFI, Inc. makes no claim of right.                            
                                                                
  Copyright (c) 2010, Byosoft Corporation. All rights reserved.
  Copyright (c) 2015, Intel Corporation. All rights reserved.
   
--*/
/*++

Module Name:

  Guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "Guid.h"


EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid001 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_001_GUID;

EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid002 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_002_GUID;

EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid003 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_003_GUID;

EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid004 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_004_GUID;

EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid005 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_005_GUID;

EFI_GUID gAbsolutePointerBBTestConformanceAssertionGuid006 = EFI_TEST_ABSOLUTEPOINTERBBTESTCONFORMANCE_ASSERTION_006_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid001 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_001_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid002 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_002_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid003 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_003_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid004 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_004_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid005 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_005_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid006 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_006_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid007 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_007_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid008 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_008_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid009 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_009_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid010 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_010_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid011 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_011_GUID;

EFI_GUID gAbsolutePointerExtensiveTestAssertionGuid012 = EFI_TEST_ABSOLUTEPOINTEREXTENSIVETEST_ASSERTION_012_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid001 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_001_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid002 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_002_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid003 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_003_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid004 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_004_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid005 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_005_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid006 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_006_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid007 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_007_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid008 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_008_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid009 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_009_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid010 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_010_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid011 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_011_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid012 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_012_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid013 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_013_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid014 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_014_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid015 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_015_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid016 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_016_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid017 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_017_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid018 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_018_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid019 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_019_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid020 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_020_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid021 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_021_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid022 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_022_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid023 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_023_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid024 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_024_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid025 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_025_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid026 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_026_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid027 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_027_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid028 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_028_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid029 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_029_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid030 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_030_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid031 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_031_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid032 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_032_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid033 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_033_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid034 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_034_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid035 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_035_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid036 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_036_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid037 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_037_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid038 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_038_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid039 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_039_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid040 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_040_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid041 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_041_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid042 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_042_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid043 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_043_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid044 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_044_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid045 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_045_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid046 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_046_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid047 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_047_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid048 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_048_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid049 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_049_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid050 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_050_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid051 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_051_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid052 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_052_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid053 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_053_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid054 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_054_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid055 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_055_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid056 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_056_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid057 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_057_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid058 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_058_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid059 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_059_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid060 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_060_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid061 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_061_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid062 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_062_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid063 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_063_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid064 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_064_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid065 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_065_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid066 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_066_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid067 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_067_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid068 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_068_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid069 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_069_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid070 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_070_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid071 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_071_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid072 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_072_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid073 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_073_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid074 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_074_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid075 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_075_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid076 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_076_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid077 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_077_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid078 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_078_GUID;

EFI_GUID gAbsolutePointerBBTestFunctionAssertionGuid079 = EFI_TEST_ABSOLUTEPOINTERBBTESTFUNCTION_ASSERTION_079_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid001 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_001_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid002 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_002_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid003 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_003_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid004 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_004_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid005 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_005_GUID;

EFI_GUID gAbsolutePointerBBTestStressAssertionGuid006 = EFI_TEST_ABSOLUTEPOINTERBBTESTSTRESS_ASSERTION_006_GUID;
