/** @file

  Copyright 2006 - 2012 Unified EFI, Inc.<BR>
  Copyright (c) 2010 - 2012, Intel Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  guid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/


#include "SimpleTextInBBTestMain.h"

EFI_GUID gSimpleTextInConformanceTestAssertionGuid002 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_002_GUID;

EFI_GUID gSimpleTextInConformanceTestAssertionGuid003 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_003_GUID;

EFI_GUID gSimpleTextInConformanceTestAssertionGuid004 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_004_GUID;

EFI_GUID gSimpleTextInConformanceTestAssertionGuid007 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_007_GUID;

EFI_GUID gSimpleTextInConformanceTestAssertionGuid008 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_008_GUID;

EFI_GUID gSimpleTextInConformanceTestAssertionGuid010 = EFI_TEST_SIMPLETEXTINCONFORMANCETEST_ASSERTION_010_GUID;

EFI_GUID gSimpleTextInExtensiveTestAssertionGuid001 = EFI_TEST_SIMPLETEXTINEXTENSIVETEST_ASSERTION_001_GUID;

EFI_GUID gSimpleTextInExtensiveTestAssertionGuid002 = EFI_TEST_SIMPLETEXTINEXTENSIVETEST_ASSERTION_002_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid001 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_001_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid002 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_002_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid003 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_003_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid004 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_004_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid005 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_005_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid006 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_006_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid007 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_007_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid008 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_008_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid009 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_009_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid010 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_010_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid011 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_011_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid012 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_012_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid013 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_013_GUID;

EFI_GUID gSimpleTextInInterfaceTestAssertionGuid014 = EFI_TEST_SIMPLETEXTININTERFACETEST_ASSERTION_014_GUID;
