/** @file

  Copyright 2006 - 2010 Unified EFI, Inc.<BR>
  Copyright (c) 2010, Phoenix Corporation. All rights reserved.<BR>

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at 
  http://opensource.org/licenses/bsd-license.php
 
  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
 
**/
/*++

Module Name:

  TapeGuid.c

Abstract:

  GUIDs auto-generated for EFI test assertion.

--*/

#include "Efi.h"
#include "TapeGuid.h"

EFI_GUID gTapeBBTestMainAssertionGuid001 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_001_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid002 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_002_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid003 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_003_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid004 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_004_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid005 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_005_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid006 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_006_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid007 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_007_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid008 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_008_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid009 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_009_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00A = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00A_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00B = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00B_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00C = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00C_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00D = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00D_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00E = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00E_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid00F = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_00F_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid010 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_010_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid011 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_011_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid012 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_012_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid013 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_013_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid014 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_014_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid015 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_015_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid016 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_016_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid017 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_017_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid018 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_018_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid019 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_019_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01A = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01A_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01B = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01B_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01C = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01C_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01D = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01D_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01E = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01E_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid01F = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_01F_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid020 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_020_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid021 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_021_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid022 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_022_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid023 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_023_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid024 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_024_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid025 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_025_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid026 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_026_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid027 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_027_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid028 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_028_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid029 = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_029_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02A = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02A_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02B = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02B_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02C = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02C_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02D = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02D_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02E = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02E_GUID;
EFI_GUID gTapeBBTestMainAssertionGuid02F = EFI_TEST_TAPE_BBTESTMAIN_ASSERTION_02F_GUID;